
//abhishek
export const FETCH_MYDATA_REQUEST="FETCH_MYDATA_REQUEST";
export const FETCH_MYDATA_SUCCESS="FETCH_MYDATA_SUCCESS";
export const FETCH_MYDATA_FAILURE="FETCH_MYDATA_FAILURE";

//rasheed's
export const FETCH_DATA_SUCCESS="FETCH_DATA_SUCCESS";
export const FETCH_DATA_REQUEST="FETCH_DATA_REQUEST";
export const FETCH_DATA_FAILURE="FETCH_DATA_FAILURE";